# Generated by Django 3.2.4 on 2021-08-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
