# Generated by Django 3.2.4 on 2021-08-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_audiofile_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='delivery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='service_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
    ]
