# Generated by Django 3.2.4 on 2021-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210802_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='actual_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='delivery_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='service_charge',
            field=models.FloatField(default=0),
        ),
    ]
