# Generated by Django 3.2.4 on 2021-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_originalaudio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalaudio',
            old_name='file',
            new_name='audioFile',
        ),
        migrations.AddField(
            model_name='originalaudio',
            name='originalFile',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
