# Generated by Django 3.2.4 on 2021-08-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210802_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalaudio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
