# Generated by Django 3.2.4 on 2021-08-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
