# Generated by Django 3.2.4 on 2021-08-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_description_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
