# Generated by Django 3.2.4 on 2021-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
