# Generated by Django 3.2.4 on 2021-08-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_userfile_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='price',
        ),
        migrations.AddField(
            model_name='userfile',
            name='actual_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='delivery_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='service_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
