# Generated by Django 3.2.4 on 2021-08-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210804_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='file_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='downloadable_file',
            field=models.FileField(default='', upload_to='cart'),
        ),
    ]
