# Generated by Django 3.2.4 on 2021-08-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210805_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubelink',
            name='link_id',
            field=models.CharField(max_length=1000),
        ),
    ]
