# Generated by Django 3.2.4 on 2021-08-05 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_youtubelink_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalaudio',
            name='id',
        ),
        migrations.AlterField(
            model_name='originalaudio',
            name='audioFile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.audiofile'),
        ),
    ]
