# Generated by Django 3.2.6 on 2021-08-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_verifyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyuser',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verifyuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
